### ISSUE TITLE
Default From value?

### ISSUE THREAD

**Issue by soya-miruku** [itsezc/lucid#4]
currently when you do a select query such as
`Account.select(['email', 'id']).where({ email: 'someemail@gmail.com' }).build();
`it does not infer the table name, i think it should do so in such a case, and if a user decides to override they can add the from query

not sure if this would be a case of just adding 
`query = query.concat(' ', 'FROM ', this.query_table || this.query_from);
`in the select builder, but yeah just wanted to raise it.

**Comment by itsezc** [comment]
Thanks for pointing this out! It's been resolved, the `refactor` branch now infers `account` as the table.
