### ISSUE TITLE
Feature Request: dynamic return types

### ISSUE THREAD

**Issue by itsezc** [itsezc/lucid#8]
### Preliminary checklist

- [X] I understand that all communication must be in English
- [X] I read the [Documentation](https://engineering.foret.ag)
- [X] I read the [Contributing guide](https://github.com/ForetagInc/.github/blob/master/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/ForetagInc/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I searched the issues and discussions but couldn't find anything (or linked relevant results below)

### Problem

Currently, the return types are linked to the `Model` of which they are called by i.e. `Account.select()` would return `Account[]`, however in some cases the developer may only select a few fields i.e. `username` and `password` and therefore returning the full type may be obsolete and provide types which are otherwise invalid.

Additionally, some field types may be sub queries, these should also be handled adequately.

### Solution

The builder needs to be aware of such functionality and ensure that only the selected field types are returned.

### Contribution

Yes, I will work on a PR

### Keywords

dynamic, queries, return, types

**Comment by soya-miruku** [comment]
the inference for when fetching a model after renaming using as is not working, will do this soon
